---
- name: Disable SELinux persistently
  ansible.posix.selinux:
    policy: targeted
    state: disabled

- name: Disable SELinux temporarily
  command: setenforce 0
  when: ansible_selinux.status == "enabled"
