---
- name: Disable SELinux persistently
  replace:
    path: /etc/selinux/config
    regexp: '^SELINUX=enforcing'
    replace: 'SELINUX=disabled'

- name: Disable SELinux temporarily
  command: setenforce 0
  when: ansible_selinux.status == "enabled"
  ignore_errors: true
