---
- name: Ensure firewalld is running (start if not active)
  service:
    name: firewalld
    state: started
    enabled: yes

- name: Open http port in firewall
  firewalld:
    service: http
    permanent: yes
    state: enabled
  notify: reload firewall