---
# Проверка на пустые значения и отсуствующие переменные
- name: Check required keys
  assert:
    that:
      - item.name is defined and item.name is not none and item.name | trim | length > 0
      - item.listen is defined and item.listen is not none and item.listen | trim | length > 0
      - item.server_name is defined and item.server_name is not none and item.server_name | trim | length > 0
      - item.root is defined and item.root is not none and item.root | trim | length > 0
    fail_msg: "Missing required key in item: {{ item }}"
  loop: "{{ sites }}"
  loop_control:
    label: "{{ item.name }}"
