---
- name: Create test html.index
  loop: "{{ sites }}"
  loop_control:
    label: "{{ item.name }}"
  template:
    dest: "{{ item.root }}/index.html"
    src: "{{ TEMPLATE_HTML }}"
    mode: 0644
  vars:
    listen_text: "{{ item.listen }}"
    server_name_text: "{{ item.server_name }}"
