---
- name: Install nginx
  package:
    name: nginx
    state: present

- name: Enable and start nginx service
  systemd:
    name: nginx
    enabled: yes
    state: started

- name: Create /storage/www directory
  file:
    path: /storage/www
    state: directory
    mode: "0775"

- name: Create symlink /var/www -> /storage/www
  file:
    src: /storage/www
    dest: /var/www
    state: link
    force: yes
